#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from ffmpymedia import __author__, __version__, __copyright__, __package__

import os.path
import datetime
import unittest
from ffmpymedia.probe import *
import ffmpymedia.parser as parser

from tests import TEST_FILE_PATH

class TestParseProbeOutput(unittest.TestCase):

    def setUp(self):
        parser.Input.reset_count()
        parser.InputStreamLineParser.reset_count()
        parser.Output.reset_count()

    def tearDown(self):
        parser.Input.reset_count()
        parser.InputStreamLineParser.reset_count()
        parser.Output.reset_count()

    def test_empty(self):
        self.assertIsNone(MediaProbe.get_params_from_ffprobe(''))

    def test_invalid_input(self):
        self.assertRaises(AttributeError, MediaProbe.get_params_from_ffprobe, 'INVALID INPUT!!!!!')

    def test_ffprobe_video01(self):
        file = os.path.join(TEST_FILE_PATH, '1 - The Gathering.avi.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'format_name': 'avi',
                          'format_long_name': 'AVI (Audio Video Interleaved)',
                          'filename': '1 - The Gathering.avi',
                          'duration': '5682.02',
                          'start_time': '0.000000',
                          'bit_rate': '1018000',
                          'tags': {'IAS1': 'English',
                                   'encoder': 'VirtualDubMod 1.5.4.1 (build 2178/release)'},
                          'streams': [{'average_frame_rate': '23.98',
                                       'bitrate': '883',
                                       'codec': 'mpeg4',
                                       'codec_long_name': 'MPEG-4 part 2',
                                       'codec_tag': '0x30355844',
                                       'codec_tag_string': 'DX50',
                                       'codec_time_base': '30k',
                                       'container_time_base': '23.98',
                                       'display_aspect_ratio': '40:31',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '496',
                                       'index': '0',
                                       'pixel_format': 'yuv420p',
                                       'reported_frame_rate': '23.98',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '640'},
                                      {'bitrate': '128000',
                                       'channel_layout': 'stereo',
                                       'channels': 2,
                                       'codec': 'mp3',
                                       'codec_long_name': 'MP3 (MPEG audio layer 3)',
                                       'codec_tag': '0x0055',
                                       'codec_tag_string': 'U[0][0][0]',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'sample_fmt': 's16p,',
                                       'sample_rate': '48000',
                                       'type': 'audio'}],})

    def test_ffprobe_video02(self):
        file = os.path.join(TEST_FILE_PATH, '[gg-BSS]_Gundam_00_S2_-_01_[44C8CD36].mkv.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'format_name': 'matroska,webm',
                          'format_long_name': 'Matroska / WebM',
                          'filename': '/media/flaviopontes/Gigante/Filmes/Anime/Gundam '
                                      '00/[gg-BSS]_Gundam_00_S2_-_01_[44C8CD36].mkv',
                          'tags': {'creation_time': '2008-10-05 18:00:56',
                                   'encoder': 'libebml v0.7.8 + libmatroska v0.8.1',
                                   'title': "[gg-BSS] Gundam 00 Second Season - 01: Angel's Advent"},
                          'duration': '1452.58',
                          'start_time': '0.000000',
                          'bit_rate': '2260000',
                          'chapters': [{'end': 129,
                                        'end_time': '129.755000',
                                        'id': '0',
                                        'metadata': {'title': 'Prologue'},
                                        'start': 0,
                                        'start_time': '0.000000',
                                        'time_base': '1/1000000000'},
                                       {'end': 706,
                                        'end_time': '706.311000',
                                        'id': '1',
                                        'metadata': {'title': 'Part One'},
                                        'start': 129,
                                        'start_time': '129.755000',
                                        'time_base': '1/1000000000'},
                                       {'end': 1260,
                                        'end_time': '1260.259000',
                                        'id': '2',
                                        'metadata': {'title': 'Part Two'},
                                        'start': 706,
                                        'start_time': '706.311000',
                                        'time_base': '1/1000000000'},
                                       {'end': 1351,
                                        'end_time': '1351.308000',
                                        'id': '3',
                                        'metadata': {'title': '"OP"'},
                                        'start': 1260,
                                        'start_time': '1260.259000',
                                        'time_base': '1/1000000000'},
                                       {'end': 1436,
                                        'end_time': '1436.101000',
                                        'id': '4',
                                        'metadata': {'title': 'lol not quite done'},
                                        'start': 1351,
                                        'start_time': '1351.308000',
                                        'time_base': '1/1000000000'},
                                       {'end': 1452,
                                        'end_time': '1452.576000',
                                        'id': '5',
                                        'metadata': {'title': 'Preview'},
                                        'start': 1436,
                                        'start_time': '1436.101000',
                                        'time_base': '1/1000000000'}],
                          'streams': [{'average_frame_rate': '23.98',
                                       'codec': 'h264',
                                       'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10',
                                       'codec_time_base': '47.95',
                                       'container_time_base': '1k',
                                       'display_aspect_ratio': '16:9',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '720',
                                       'index': '0',
                                       'language': 'jpn',
                                       'metadata': {'title': 'Gundam 00 Second Season - 01: '
                                                             "Angel's Advent"},
                                       'pixel_format': 'yuv420p',
                                       'profile': 'High',
                                       'reported_frame_rate': '23.98',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '1280'},
                                      {'channel_layout': 'stereo',
                                       'channels': 2,
                                       'codec': 'aac',
                                       'codec_long_name': 'AAC (Advanced Audio Coding)',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'language': 'jpn',
                                       'metadata': {'title': 'AAC 2.0'},
                                       'profile': 'LC',
                                       'sample_fmt': 'fltp',
                                       'sample_rate': '48000',
                                       'type': 'audio'},
                                      {'codec': 'ass',
                                       'codec_long_name': 'ASS (Advanced SubStation Alpha) subtitle',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '2',
                                       'language': 'eng',
                                       'metadata': {'title': 'Styled Subtitles'},
                                       'type': 'subtitle'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '3',
                                       'metadata': {'filename': 'Commerce_Black_Condensed_SSi_Bold_Condensed.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '4',
                                       'metadata': {'filename': 'Essai.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '5',
                                       'metadata': {'filename': 'kochi-mincho-subst.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '6',
                                       'metadata': {'filename': 'KozMinPro-Medium.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'}]})

    def test_ffprobe_video03(self):
        file = os.path.join(TEST_FILE_PATH, '[HorribleSubs] Fairy Tail S2 - 52 [720p].mkv.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '1902000',
                          'duration': '1464.97',
                          'filename': '/media/flaviopontes/Gigante/Filmes/Anime/Fairy '
                                      'Tail/[HorribleSubs] Fairy Tail S2 - 52 [720p].mkv',
                          'format_long_name': 'Matroska / WebM',
                          'format_name': 'matroska,webm',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '23.81',
                                       'codec': 'h264',
                                       'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10',
                                       'codec_time_base': '47.95',
                                       'container_time_base': '1k',
                                       'display_aspect_ratio': '16:9',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 1,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '720',
                                       'index': '0',
                                       'pixel_format': 'yuv420p',
                                       'profile': 'High',
                                       'reported_frame_rate': '23.81',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '1280'},
                                      {'channel_layout': 'stereo',
                                       'channels': 2,
                                       'codec': 'aac',
                                       'codec_long_name': 'AAC (Advanced Audio Coding)',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 1,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'profile': 'LC',
                                       'sample_fmt': 'fltp',
                                       'sample_rate': '44100',
                                       'type': 'audio'},
                                      {'codec': 'ass',
                                       'codec_long_name': 'ASS (Advanced SubStation Alpha) subtitle',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 1,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '2',
                                       'type': 'subtitle'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '3',
                                       'metadata': {'filename': 'BAARS___.TTF',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'}],
                          'tags': {'creation_time': '1970-01-01 00:00:00',
                                   'encoder': 'no_variable_data'}})

    def test_ffprobe_video04(self):
        file = os.path.join(TEST_FILE_PATH, 'Akira - 1988 [eng] dvdrip xvid [Honeyko].avi.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '780000',
                          'duration': '7527.86',
                          'filename': '/media/flaviopontes/Gigante/Filmes/Anime/Akira - 1988 [eng] '
                                      'dvdrip xvid [Honeyko]/Akira - 1988 [eng] dvdrip xvid '
                                      '[Honeyko].avi',
                          'format_long_name': 'AVI (Audio Video Interleaved)',
                          'format_name': 'avi',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '23.98',
                                       'bitrate': '652',
                                       'codec': 'mpeg4',
                                       'codec_long_name': 'MPEG-4 part 2',
                                       'codec_tag': '0x44495658',
                                       'codec_tag_string': 'XVID',
                                       'codec_time_base': '23.98',
                                       'container_time_base': '23.98',
                                       'display_aspect_ratio': '45:26',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '416',
                                       'index': '0',
                                       'pixel_format': 'yuv420p',
                                       'profile': 'Advanced Simple Profile',
                                       'reported_frame_rate': '23.98',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '720'},
                                      {'bitrate': '114000',
                                       'channel_layout': 'stereo',
                                       'channels': 2,
                                       'codec': 'mp3',
                                       'codec_long_name': 'MP3 (MPEG audio layer 3)',
                                       'codec_tag': '0x0055',
                                       'codec_tag_string': 'U[0][0][0]',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'sample_fmt': 's16p,',
                                       'sample_rate': '48000',
                                       'type': 'audio'}],
                          'tags': {'IAS1': '???',
                                   'encoder': 'VirtualDubMod 1.5.4.1 (build 2178/release)'}})

    def test_ffprobe_video05(self):
        file = os.path.join(TEST_FILE_PATH, 'AULA PROFISSOES.mov.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '34926000',
                          'duration': '946.41',
                          'filename': 'AULA PROFISSOES.mov',
                          'format_long_name': 'QuickTime / MOV',
                          'format_name': 'mov,mp4,m4a,3gp,3g2,mj2',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '29.97',
                                       'bitrate': '33386',
                                       'codec': 'mpeg2video',
                                       'codec_long_name': 'MPEG-2 video',
                                       'codec_tag': '0x62766478',
                                       'codec_tag_string': 'xdvb',
                                       'codec_time_base': '59.94',
                                       'color_range': 'tv',
                                       'color_space': 'bt709',
                                       'container_time_base': '2997',
                                       'display_aspect_ratio': '16:9',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1080',
                                       'index': '0',
                                       'language': 'eng',
                                       'metadata': {'creation_time': datetime.datetime(2014, 4, 3, 18, 19, 14),
                                                    'encoder': 'XDCAM EX 1080i60 (35 Mb/s VBR)',
                                                    'handler_name': 'Apple Alias Data Handler',
                                                    'timecode': '01:00:00;00'},
                                       'pixel_format': 'yuv420p',
                                       'profile': 'Main',
                                       'reported_frame_rate': '29.97',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '1920'},
                                      {'bitrate': '768000',
                                       'channel_layout': '1 channels',
                                       'codec': 'pcm_s16le',
                                       'codec_long_name': 'PCM signed 16-bit little-endian',
                                       'codec_tag': '0x74776F73',
                                       'codec_tag_string': 'sowt',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'language': 'eng',
                                       'metadata': {'creation_time': datetime.datetime(2014, 4, 3, 18, 19, 14),
                                                    'handler_name': 'Apple Alias Data Handler'},
                                       'sample_fmt': 's16,',
                                       'sample_rate': '48000',
                                       'type': 'audio'},
                                      {'bitrate': '768000',
                                       'channel_layout': '1 channels',
                                       'codec': 'pcm_s16le',
                                       'codec_long_name': 'PCM signed 16-bit little-endian',
                                       'codec_tag': '0x74776F73',
                                       'codec_tag_string': 'sowt',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '2',
                                       'language': 'eng',
                                       'metadata': {'creation_time': datetime.datetime(2014, 4, 3, 18, 19, 14),
                                                    'handler_name': 'Apple Alias Data Handler'},
                                       'sample_fmt': 's16,',
                                       'sample_rate': '48000',
                                       'type': 'audio'},
                                      {'codec': 'none',
                                       'codec_tag': '0x64636D74',
                                       'codec_tag_string': 'tmcd',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '3',
                                       'language': 'eng',
                                       'metadata': {'creation_time': datetime.datetime(2014, 4, 3, 18, 19, 14),
                                                    'handler_name': 'Apple Alias Data Handler',
                                                    'timecode': '01:00:00;00'},
                                       'type': 'data'}],
                          'tags': {'compatible_brands': 'qt',
                                   'creation_time': '2014-04-03 18:19:14',
                                   'major_brand': 'qt',
                                   'minor_version': '537199360'}})

    def test_ffprobe_video06(self):
        file = os.path.join(TEST_FILE_PATH, 'b5c.s01e01.war_zone.dvdrip_xvid-medieval.avi.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '1100000',
                          'duration': '2655.66',
                          'filename': '/media/flaviopontes/Gigante/Babylon 5/B5 Crusade '
                                      '1-13/b5c.s01e01.war_zone.dvdrip_xvid-medieval.avi',
                          'format_long_name': 'AVI (Audio Video Interleaved)',
                          'format_name': 'avi',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '23.98',
                                       'bitrate': '958',
                                       'codec': 'mpeg4',
                                       'codec_long_name': 'MPEG-4 part 2',
                                       'codec_tag': '0x44495658',
                                       'codec_tag_string': 'XVID',
                                       'codec_time_base': '23.98',
                                       'container_time_base': '23.98',
                                       'display_aspect_ratio': '4:3',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '432',
                                       'index': '0',
                                       'pixel_format': 'yuv420p',
                                       'profile': 'Advanced Simple Profile',
                                       'reported_frame_rate': '23.98',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '576'},
                                      {'bitrate': '129000',
                                       'channel_layout': 'stereo',
                                       'channels': 2,
                                       'codec': 'mp3',
                                       'codec_long_name': 'MP3 (MPEG audio layer 3)',
                                       'codec_tag': '0x0055',
                                       'codec_tag_string': 'U[0][0][0]',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'sample_fmt': 's16p,',
                                       'sample_rate': '48000',
                                       'type': 'audio'}],
                          'tags': {'encoder': 'Nandub v1.0rc2'}})

    def test_ffprobe_video07(self):
        file = os.path.join(TEST_FILE_PATH, 'Berserk_Golden_Age_Arc_I_Egg_of_the_Supreme_Ruler_(2012)_[1080p,BluRay,flac,x264]_-_Taka-THORA.mkv.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '7102000',
                          'duration': '4610.03',
                          'filename': '/media/flaviopontes/Gigante/Filmes/Anime/Berserk_Golden_Age_Arc_I_Egg_of_the_Supreme_Ruler_(2012)_[1080p,BluRay,flac,x264]_-_Taka-THORA/Berserk_Golden_Age_Arc_I_Egg_of_the_Supreme_Ruler_(2012)_[1080p,BluRay,flac,x264]_-_Taka-THORA.mkv',
                          'format_long_name': 'Matroska / WebM',
                          'format_name': 'matroska,webm',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '23.98',
                                       'codec': 'h264',
                                       'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10',
                                       'codec_time_base': '47.95',
                                       'container_time_base': '1k',
                                       'display_aspect_ratio': '40:17',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '816',
                                       'index': '0',
                                       'language': 'jpn',
                                       'pixel_format': 'yuv420p10le',
                                       'profile': 'High 10',
                                       'reported_frame_rate': '23.98',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '1920'},
                                      {'bits_per_raw_sample': '24',
                                       'channel_layout': '5.1(side)',
                                       'channels': 6,
                                       'codec': 'flac',
                                       'codec_long_name': 'FLAC (Free Lossless Audio Codec)',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'language': 'jpn',
                                       'sample_fmt': 's32',
                                       'sample_rate': '48000',
                                       'type': 'audio'},
                                      {'codec': 'ass',
                                       'codec_long_name': 'ASS (Advanced SubStation Alpha) subtitle',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '2',
                                       'language': 'eng',
                                       'type': 'subtitle'},
                                      {'codec': 'otf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '3',
                                       'metadata': {'filename': 'A-OTF-Reisho101Std-Medium.otf',
                                                    'mimetype': 'application/vnd.ms-opentype'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '4',
                                       'metadata': {'filename': 'calibri.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'none',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '5',
                                       'metadata': {'filename': 'DFKaiC.ttc',
                                                    'mimetype': 'application/octet-stream'},
                                       'type': 'attachment'},
                                      {'codec': 'none',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '6',
                                       'metadata': {'filename': 'DFKyks4.ttc',
                                                    'mimetype': 'application/octet-stream'},
                                       'type': 'attachment'},
                                      {'codec': 'otf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '7',
                                       'metadata': {'filename': 'ElysiumStd-Medium.otf',
                                                    'mimetype': 'application/vnd.ms-opentype'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '8',
                                       'metadata': {'filename': 'fansubBlock.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'otf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '9',
                                       'metadata': {'filename': 'SyndorITCStd-Medium.otf',
                                                    'mimetype': 'application/vnd.ms-opentype'},
                                       'type': 'attachment'}],
                          'tags': {'creation_time': '2012-06-10 09:30:16',
                                   'encoder': 'libebml v1.2.3 + libmatroska v1.3.0',
                                   'title': 'Berserk Golden Age Arc I: Egg of the Supreme Ruler '
                                            '(2012)'}})

    def test_ffprobe_video08(self):
        file = os.path.join(TEST_FILE_PATH, 'Ghost_in_the_Shell_Arise_Ep_1_[1080p,BluRay,aac,x264]_-_THORA.mkv.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '10726000',
                          'duration': '3502.55',
                          'filename': 'Ghost_in_the_Shell_Arise_Ep_1_[1080p,BluRay,aac,x264]_-_THORA.mkv',
                          'format_long_name': 'Matroska / WebM',
                          'format_name': 'matroska,webm',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '23.98',
                                       'codec': 'h264',
                                       'codec_long_name': 'H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10',
                                       'codec_time_base': '47.95',
                                       'color_range': 'tv',
                                       'color_space': 'bt709/unknown/unknown',
                                       'container_time_base': '1k',
                                       'display_aspect_ratio': '16:9',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1080',
                                       'index': '0',
                                       'language': 'jpn',
                                       'pixel_format': 'yuv420p10le',
                                       'profile': 'High 10',
                                       'reported_frame_rate': '23.98',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '1920'},
                                      {'channel_layout': '5.1',
                                       'channels': 6,
                                       'codec': 'aac',
                                       'codec_long_name': 'AAC (Advanced Audio Coding)',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'language': 'jpn',
                                       'profile': 'LC',
                                       'sample_fmt': 'fltp',
                                       'sample_rate': '48000',
                                       'type': 'audio'},
                                      {'codec': 'ass',
                                       'codec_long_name': 'ASS (Advanced SubStation Alpha) subtitle',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 1,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '2',
                                       'language': 'eng',
                                       'type': 'subtitle'},
                                      {'codec': 'hdmv_pgs_subtitle',
                                       'codec_long_name': 'HDMV Presentation Graphic Stream subtitles',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '3',
                                       'language': 'chi',
                                       'type': 'subtitle'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '4',
                                       'metadata': {'filename': 'MyriadPro-Ar_0.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '5',
                                       'metadata': {'filename': 'MyriadPro-ArI_0.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '6',
                                       'metadata': {'filename': 'arial.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '7',
                                       'metadata': {'filename': 'tahoma.ttf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'},
                                      {'codec': 'ttf',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '8',
                                       'metadata': {'filename': 'ITCFranklinGothicStd-MdCd.otf',
                                                    'mimetype': 'application/x-truetype-font'},
                                       'type': 'attachment'}],
                          'tags': {'creation_time': '2013-07-03 20:04:34',
                                   'encoder': 'libebml v1.2.1 + libmatroska v1.1.1',
                                   'title': 'Ghost in the Shell Arise - border1: Ghost Pain'}})

    def test_ffprobe_video09(self):
        file = os.path.join(TEST_FILE_PATH, 'PANORAMA 20 VOD.mxf.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '27980000',
                          'duration': '33.1',
                          'filename': 'PANORAMA 20 VOD.mxf',
                          'format_long_name': 'MXF (Material eXchange Format)',
                          'format_name': 'mxf',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '29.97',
                                       'codec': 'mpeg2video',
                                       'codec_long_name': 'MPEG-2 video',
                                       'codec_time_base': '59.94',
                                       'color_range': 'tv',
                                       'color_space': 'unknown/bt709/bt709',
                                       'container_time_base': '29.97',
                                       'display_aspect_ratio': '16:9',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1080',
                                       'index': '0',
                                       'max_bit_rate': '35000',
                                       'metadata': {'file_package_name': 'Source Package',
                                                    'file_package_umid': '0x060A2B340101010501010D1213D47D7E0BD3380484710583497800090FFE0001'},
                                       'pixel_format': 'yuv420p',
                                       'profile': 'Main',
                                       'reported_frame_rate': '29.97',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '1920'},
                                      {'bitrate': '768000',
                                       'channel_layout': '1 channels',
                                       'codec': 'pcm_s16le',
                                       'codec_long_name': 'PCM signed 16-bit little-endian',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '1',
                                       'metadata': {'file_package_name': 'Source Package',
                                                    'file_package_umid': '0x060A2B340101010501010D1213D47D7E0BD3380484710583497800090FFE0001'},
                                       'sample_fmt': 's16,',
                                       'sample_rate': '48000',
                                       'type': 'audio'},
                                      {'bitrate': '768000',
                                       'channel_layout': '1 channels',
                                       'codec': 'pcm_s16le',
                                       'codec_long_name': 'PCM signed 16-bit little-endian',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '2',
                                       'metadata': {'file_package_name': 'Source Package',
                                                    'file_package_umid': '0x060A2B340101010501010D1213D47D7E0BD3380484710583497800090FFE0001'},
                                       'sample_fmt': 's16,',
                                       'sample_rate': '48000',
                                       'type': 'audio'}],
                          'tags': {'application_platform': 'win32',
                                   'company_name': 'Adobe Systems Incorporated',
                                   'generation_uid': 'b913ce8b-1071-11e5-9383-00090ffe0001',
                                   'material_package_umid': '0x060A2B340101010501010D11130000000DD3380484710583050500090FFE0001',
                                   'modification_date': '2015-06-11 19:40:32',
                                   'product_name': 'Adobe Media Encoder',
                                   'product_uid': '10ab07a9-e89e-7510-a923-ea9220524153',
                                   'product_version': '8.2.0',
                                   'timecode': '00:00:00;00',
                                   'uid': 'b913ce8a-1071-11e5-8c98-00090ffe0001'}})

    def test_ffprobe_imagem01(self):
        file = os.path.join(TEST_FILE_PATH, 'Cover-akira.jpg.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '11211000',
                          'duration': '0.04',
                          'filename': '/media/flaviopontes/Gigante/Filmes/Anime/Akira - 1988 [eng] '
                                      'dvdrip xvid [Honeyko]/Cover-akira.jpg',
                          'format_long_name': 'image2 sequence',
                          'format_name': 'image2',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '25',
                                       'codec': 'mjpeg',
                                       'codec_long_name': 'MJPEG (Motion JPEG)',
                                       'codec_time_base': '25',
                                       'color_range': 'pc',
                                       'color_space': 'bt470bg/unknown/unknown',
                                       'container_time_base': '25',
                                       'display_aspect_ratio': '643:907',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '907',
                                       'index': '0',
                                       'pixel_format': 'yuvj420p',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '643'}]})

    def test_ffprobe_imagem02(self):
        file = os.path.join(TEST_FILE_PATH, 'teste.bmp.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': 0,
                          'duration': 0,
                          'filename': 'teste.bmp',
                          'format_long_name': 'piped bmp sequence',
                          'format_name': 'bmp_pipe',
                          'streams': [{'average_frame_rate': '25',
                                       'codec': 'bmp',
                                       'codec_long_name': 'BMP (Windows and OS/2 bitmap)',
                                       'codec_time_base': '25',
                                       'container_time_base': '25',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1056',
                                       'index': '0',
                                       'pixel_format': 'abgr',
                                       'type': 'video',
                                       'width': '663'}]})

    def test_ffprobe_imagem03(self):
        file = os.path.join(TEST_FILE_PATH, 'teste.gif.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': 0,
                          'duration': 0,
                          'filename': 'teste.gif',
                          'format_long_name': 'CompuServe Graphics Interchange Format (GIF)',
                          'format_name': 'gif',
                          'streams': [{'average_frame_rate': '100',
                                       'codec': 'gif',
                                       'codec_long_name': 'GIF (Graphics Interchange Format)',
                                       'codec_time_base': '100',
                                       'container_time_base': '100',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1056',
                                       'index': '0',
                                       'pixel_format': 'bgra',
                                       'type': 'video',
                                       'width': '663'}]})

    def test_ffprobe_imagem04(self):
        file = os.path.join(TEST_FILE_PATH, 'teste.pgm.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '140036000',
                          'duration': '0.04',
                          'filename': 'teste.pgm',
                          'format_long_name': 'image2 sequence',
                          'format_name': 'image2',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '25',
                                       'codec': 'pgm',
                                       'codec_long_name': 'PGM (Portable GrayMap) image',
                                       'codec_time_base': '25',
                                       'container_time_base': '25',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1056',
                                       'index': '0',
                                       'pixel_format': 'gray',
                                       'type': 'video',
                                       'width': '663'}]})

    def test_ffprobe_imagem05(self):
        file = os.path.join(TEST_FILE_PATH, 'teste.pix.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': 0,
                          'duration': 0,
                          'filename': 'teste.pix',
                          'format_long_name': 'Alias/Wavefront PIX image',
                          'format_name': 'alias_pix',
                          'streams': [{'average_frame_rate': '25',
                                       'codec': 'alias_pix',
                                       'codec_long_name': 'Alias/Wavefront PIX image',
                                       'codec_time_base': '25',
                                       'container_time_base': '25',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1056',
                                       'index': '0',
                                       'pixel_format': 'bgr24',
                                       'type': 'video',
                                       'width': '663'}]})

    def test_ffprobe_imagem06(self):
        file = os.path.join(TEST_FILE_PATH, 'teste.png.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': 0,
                          'duration': 0,
                          'filename': 'teste.png',
                          'format_long_name': 'piped png sequence',
                          'format_name': 'png_pipe',
                          'streams': [{'average_frame_rate': '25',
                                       'codec': 'png',
                                       'codec_long_name': 'PNG (Portable Network Graphics) image',
                                       'codec_time_base': '25',
                                       'container_time_base': '25',
                                       'display_aspect_ratio': '221:352',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1056',
                                       'index': '0',
                                       'pixel_format': 'rgba',
                                       'sample_aspect_ratio': '2835:2835',
                                       'type': 'video',
                                       'width': '663'}]})

    def test_ffprobe_imagem07(self):
        file = os.path.join(TEST_FILE_PATH, 'teste.tga.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': '80418000',
                          'duration': '0.04',
                          'filename': 'teste.tga',
                          'format_long_name': 'image2 sequence',
                          'format_name': 'image2',
                          'start_time': '0.000000',
                          'streams': [{'average_frame_rate': '25',
                                       'codec': 'targa',
                                       'codec_long_name': 'Truevision Targa image',
                                       'codec_time_base': '25',
                                       'container_time_base': '25',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1056',
                                       'index': '0',
                                       'pixel_format': 'bgra',
                                       'type': 'video',
                                       'width': '663'}]})

    def test_ffprobe_imagem08(self):
        file = os.path.join(TEST_FILE_PATH, 'teste.tiff.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': 0,
                          'duration': 0,
                          'filename': 'teste.tiff',
                          'format_long_name': 'piped tiff sequence',
                          'format_name': 'tiff_pipe',
                          'streams': [{'average_frame_rate': '25',
                                       'codec': 'tiff',
                                       'codec_long_name': 'TIFF image',
                                       'codec_time_base': '25',
                                       'container_time_base': '25',
                                       'display_aspect_ratio': '221:352',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'height': '1056',
                                       'index': '0',
                                       'pixel_format': 'rgba',
                                       'sample_aspect_ratio': '1:1',
                                       'type': 'video',
                                       'width': '663'}]})

    def test_ffprobe_subtitle01(self):
        file = os.path.join(TEST_FILE_PATH, 'My Neighbour Totoro (twin audio).srt.ffprobe')
        self.assertEqual(MediaProbe.get_params_from_ffprobe(open(file, 'r')),
                         {'bit_rate': 0,
                          'duration': 0,
                          'filename': '/media/flaviopontes/Gigante/Filmes/Anime/Studio Ghibli/My '
                                      'Neighbour Totoro/My Neighbour Totoro (twin audio).srt',
                          'format_long_name': '',
                          'format_name': 'srt',
                          'streams': [{'codec': 'subrip',
                                       'codec_long_name': 'SubRip subtitle',
                                       'disposition': {'attached_pic': 0,
                                                       'clean_effects': 0,
                                                       'comment': 0,
                                                       'default': 0,
                                                       'dub': 0,
                                                       'forced': 0,
                                                       'hearing_impaired': 0,
                                                       'karaoke': 0,
                                                       'lyrics': 0,
                                                       'original': 0,
                                                       'visual_impaired': 0},
                                       'index': '0',
                                       'type': 'subtitle'}]})
